Repository vattenbagarna/Frontend, pull requests merged in 2019-05, with the labels that each got.

#90 fixed bugs #88, #74 and added #89 feature
  js/map/classes.js
  js/map/edit.js
  js/map/loadLeafletMap.js
  js/map/show.js
  map.html
Labels: Sprint 5

#101 API middleware
  home.html
  js/APIMiddleware.js
  js/map/edit.js
  js/map/loadLeafletMap.js
  js/products/listProducts.js
  js/products/newObject.js
  js/products/updateObject.js
  js/projects/home.js
  js/projects/newproject.js
  js/projects/updateproject.js
  listProducts.html
  map.html
  newObject.html
  newproject.html
  updateObject.html
  updateProject.html
Labels: Sprint 5

#106 fixed api middleware
  js/APIMiddleware.js
Labels: CRITICAL

#105 Fix calculations site
  .gitignore
  calculations.html
  css/calculations.css
  js/calculations/flowCalc.js
  map.html
Labels: Sprint 6

#99 Load b64 images
  img/exampleIcon.png
  img/symbol_grenanslutning.png
  js/map/add.js
  js/map/classes.js
  js/map/edit.js
  js/map/loadLeafletMap.js
  js/map/options.js
  js/products/newObject.js
  js/products/updateObject.js
  map.html
Labels: Sprint 6

#100 Added so that polylines get elevation data when they are created.
  js/map/classes.js
  js/map/edit.js
  js/map/show.js
Labels: Sprint 6

#112 Updated pipes options when placing on map
  css/map.css
  js/map/add.js
  js/map/classes.js
  js/map/edit.js
  js/map/loadLeafletMap.js
  js/map/pipes.js
  js/map/popup.js
  js/map/show.js
  map.html
Labels: Sprint 6

#114 Added mu
  calculations.html
  js/calculations/flowCalc.js
  js/exportCalc.js
Labels: Sprint 6, fix

#116 Map bug fix
  js/map/add.js
  js/map/loadLeafletMap.js
  map.html
Labels: Sprint 6, bug

#103 All external js libraries are now stored locally.
  .eslintignore
  js/vendor/chart.min.js
  js/vendor/esri-leaflet-geocoder.js
  js/vendor/esri-leaflet.js
  js/vendor/leaflet-draggable-polyline.js
  js/vendor/leaflet.geometryutil.js
  js/vendor/leaflet.googleMutant.js
  js/vendor/leaflet.js
  js/vendor/leaflet.polylineDecorator.js
  map.html
  materiallist.html
  newObject.html
  updateObject.html
Labels: Sprint 6

#118 Changed popup for polylines.
  css/map.css
  js/map/classes.js
  js/map/pipes.js
  js/map/popup.js
  map.html
Labels: Sprint 6

#125 fixed some small changes to the GUI
  changepassword.html
  home.html
  js/map/popup.js
  js/products/newObject.js
  newObject.html
  updateObject.html
Labels: Sprint 6, fix

#131 Show popup on arrows and remove when editing
  js/map/classes.js
  js/map/edit.js
  js/map/loadLeafletMap.js
Labels: Sprint 6, bug

#129 Small fixes
  css/map.css
  js/APIMiddleware.js
  js/map/add.js
  js/map/classes.js
  js/map/edit.js
  js/map/loadLeafletMap.js
  js/map/popup.js
  map.html
Labels: Sprint 6

#122 Material list print, fixed amount of pumps
  css/map.css
  css/materiallist.css
  js/configVariables.js
  js/map/loadLeafletMap.js
  js/map/loadLeafletMaterialMap.js
  materiallist.html
Labels: Sprint 6

#132 Calculations on map
  css/map.css
  css/materiallist.css
  js/calculations/flowCalc.js
  js/configVariables.js
  js/exportCalc.js
  js/map/add.js
  js/map/classes.js
  js/map/edit.js
  js/map/getKeyExample.js
  js/map/loadLeafletMap.js
  js/map/loadLeafletMaterialMap.js
  js/map/pipes.js
  js/map/show.js
  map.html
  materiallist.html
Labels: Sprint 6

#136 added gridlayer and small css change
  js/map/loadLeafletMap.js
Labels: bug

#137 added linebreaks after username
  css/home.css
  js/projects/home.js
Labels: bug, fix

#140 Bug fixes
  js/map/add.js
  js/map/classes.js
  js/map/loadLeafletMap.js
Labels: bug

#149 Fix calc site
  calculations.html
  js/calculations/flowCalc.js
Labels: bug, fix

#154 finally fixed space
  js/calculations/flowCalc.js
Labels: bug, fix

#157 Moved a file to the correct map and made som small changes in GUI
  calculations.html
  js/calculations/exportCalc.js
  js/calculations/flowCalc.js
  map.html
Labels: fix

#167 fixed a bug where guideline was not removed when doing other stuff
  js/map/classes.js
  js/map/edit.js
Labels: bug

#168 Repair calc validation
  calculations.html
  js/calculations/flowCalc.js
Labels: bug
